# configs/xeuss.yml
name: Xeuss1800HR
detector: Eiger1M
detector_distance_m: 1.8
wavelength_A: 1.54
flux_ph_s: 3.43e6
exposure_s: 1200
# beamstop_mask: masks/eiger1m.msk   # disable on Windows if mask file missing
# axis_out: axis.dat   # optional; if present, im2dat will reuse it
